# !/bin/bash
set -e

export PATH=/opt/st/stm32cubeide_1.16.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.12.3.rel1.linux64_1.1.0.202410170702/tools/bin:$PATH

if [ -f *.o ]; then
    rm *.o
fi

arm-none-eabi-gcc -mcpu=cortex-m7 -g3 -c -Wall -Wextra -x assembler-with-cpp --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f746xx.s

arm-none-eabi-gcc Drivers/BSP/exc7200/exc7200.c -IDrivers/BSP/exc7200/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/ft5336/ft5336.c -IDrivers/BSP/ft5336/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/mfxstm32l152/mfxstm32l152.c -IDrivers/BSP/mfxstm32l152 -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/ov9655/ov9655.c -IDrivers/BSP/ov9655/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/s5k5cag/s5k5cag.c -IDrivers/BSP/s5k5cag/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/st7735/st7735.c -IDrivers/BSP/st7735/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/stmpe811/stmpe811.c -IDrivers/BSP/stmpe811/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/ts3510/ts3510.c -IDrivers/BSP/ts3510/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/wm8994/wm8994.c -IDrivers/BSP/wm8994/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery.c -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_audio.c -IDrivers/BSP/wm8994/ -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_eeprom.c -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_lcd.c -IDrivers/BSP/rk043fn48h -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_sd.c -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_sdram.c -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/BSP/STM32746G_DISCOVERY/stm32746g_discovery_ts.c -IDrivers/BSP/ft5336/ -IDrivers/BSP/STM32746G_DISCOVERY/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/system_stm32f7xx.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc -mcpu=cortex-m7 -g3 -c -Wall -Wextra -x assembler-with-cpp --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb "DSP_CMSIS/arm_bitreversal2.s"
arm-none-eabi-gcc DSP_CMSIS/arm_bitreversal.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cfft_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cfft_radix2_init_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cfft_radix2_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cfft_radix4_init_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cfft_radix4_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_cmplx_mag_squared_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_common_tables.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_const_structs.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_fir_decimate_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_fir_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_rfft_init_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_rfft_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_scale_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc DSP_CMSIS/arm_shift_q15.c -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc FT8_library/constants.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/decode.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/encode.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/ldpc.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/pack.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/text.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc FT8_library/unpack.c -IFT8_library/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc Middlewares/src/ccsbcs.c -IMiddlewares/src/ -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/diskio.c -IMiddlewares/src/ -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/ff.c -IMiddlewares/src/ -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/ff_gen_drv.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/sdram_diskio.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/sd_diskio.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/unicode.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Middlewares/src/option/syscall.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc Src/ADIF.c -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/button.c -IDrivers/BSP/STM32746G_DISCOVERY -IFT8_library/ -IUtilities -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/Codec_Gains.c -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/wm8994/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/decode_ft8.c -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/rk043fn48h/ -IFT8_library -IUtilities -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/Display.c -IDrivers/BSP/STM32746G_DISCOVERY -IFT8_library/ -IUtilities/ -IDrivers/BSP/ft5336/ -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/DS3231.c -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/rk043fn48h/ -IUtilities -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/FIR_Coefficients.c -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/gen_ft8.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src -IFT8_library/ -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/log_file.c -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/ft5336/ -IDrivers/BSP/rk043fn48h/ -IMiddlewares/src/ -IUtilities -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/main.c -IDrivers/BSP/STM32746G_DISCOVERY -IUtilities -IFT8_library/ -IDrivers/BSP/rk043fn48h/ -IDrivers/BSP/ft5336/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/options.c -IDrivers/BSP/STM32746G_DISCOVERY -IMiddlewares/src/ -IUtilities/ -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/Process_DSP.c -IDrivers/BSP/STM32746G_DISCOVERY -IFT8_library -IUtilities -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/SDR_Audio.c -IDrivers/BSP/STM32746G_DISCOVERY -IFT8_library/ -IDrivers/BSP/rk043fn48h/ -IDrivers/BSP/wm8994/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/SiLabs.c -IDrivers/BSP/STM32746G_DISCOVERY -IUtilities -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/Sine_table.c -IDrivers/BSP/STM32746G_DISCOVERY -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/stm32f7xx_it.c -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/wm8994/ -IUtilities -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra
arm-none-eabi-gcc Src/traffic_manager.c -IFT8_library -IUtilities -IDrivers/BSP/STM32746G_DISCOVERY -IDrivers/BSP/rk043fn48h/ -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -c -IInc -IDrivers/CMSIS/Include -IDrivers/CMSIS/Device/ST/STM32F7xx/Include -IDrivers/STM32F7xx_HAL_Driver/Inc -IDrivers/BSP/STM32746G-Discovery -IDrivers/BSP/Common -IUtilities/Fonts -Os -ffunction-sections  --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wall -Wextra

arm-none-eabi-gcc -o "Katy.elf" *.o -Wall -Wextra -mcpu=cortex-m7 -T"STM32F746NGHx_FLASH.ld" --specs=nosys.specs -Wl,-Map="Katy.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group

arm-none-eabi-size Katy.elf 
arm-none-eabi-objdump -h -S Katy.elf > "Katy.list"
arm-none-eabi-objcopy -O binary Katy.elf "Katy.bin"

rm *.o
